"""add composite indexes on events order_id+event_type and vacancy_id+event_type

Revision ID: 214045ca6187
Revises: 0debf505d8f8
Create Date: 2026-09-26 01:29:15.068513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214045ca6187'
down_revision: Union[str, Sequence[str], None] = '0debf505d8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_order_id'), table_name='events')
    op.drop_index(op.f('ix_events_vacancy_id'), table_name='events')
    op.create_index('ix_events_order_id_event_type', 'events', ['order_id', 'event_type'], unique=False)
    op.create_index('ix_events_vacancy_id_event_type', 'events', ['vacancy_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_vacancy_id_event_type', table_name='events')
    op.drop_index('ix_events_order_id_event_type', table_name='events')
    op.create_index(op.f('ix_events_vacancy_id'), 'events', ['vacancy_id'], unique=False)
    op.create_index(op.f('ix_events_order_id'), 'events', ['order_id'], unique=False)
    # ### end Alembic commands ###
