"""add site_href to vacancies and orders

Revision ID: f8a851826b23
Revises: 214045ca6187
Create Date: 2026-09-26 20:32:51.809020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a851826b23'
down_revision: Union[str, Sequence[str], None] = '214045ca6187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orders', sa.Column('site_href', sa.String(length=255), nullable=True))
    op.add_column('vacancies', sa.Column('site_href', sa.String(length=255), nullable=True))

    op.execute("""
        UPDATE vacancies
        SET site_href = CASE platform
            WHEN 'hh' THEN 'https://hh.ru/vacancy/' || platform_id::text
            WHEN 'habr' THEN 'https://career.habr.com/vacancies/' || platform_id::text
        END
    """)
    op.execute("""
        UPDATE orders
        SET site_href = CASE platform
            WHEN 'fl' THEN 'https://www.fl.ru/projects/' || platform_id::text
            WHEN 'kwork' THEN 'https://kwork.ru/projects/' || platform_id::text || '/view'
        END
    """)

    # Every row now has a value - enforce NOT NULL as the model declares.
    op.alter_column('orders', 'site_href', nullable=False)
    op.alter_column('vacancies', 'site_href', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'site_href')
    op.drop_column('orders', 'site_href')
    # ### end Alembic commands ###
